/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "ff3.0--ijk0.5.0--dev0.4.5--rc11"
#endif /* AVUTIL_FFVERSION_H */
